import type { Metadata } from "next";
import "./globals.css";
// import { Utendo } from "@/utils/fonts";
import { Outfit } from "next/font/google"


const outfit = Outfit({
  display: "swap",
  variable: "--font-outfit"
})



export const metadata: Metadata = {
  title: "Carebond",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`text-pretty  ${outfit.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
